---
title: "Dr. Waldrop's Odor-capture Notebook"
output: html_notebook
fig_width: 6
---

# Some initial plotting for the water condition

Loading data and shaping data frame:
```{r echo=TRUE, message=TRUE, warning=FALSE}
library(ggplot2) # for ggplots
library(cowplot)
library(reshape2) # for melt()
library(viridis) # for the viridis color palette

# Sourcing data handling functions
source("../src/r-scripts/datahandling_functions.R")

n <- 165 # Number of simulations in set

# Loading individual data sets
waterdata_3 <- loadnshapedata(n,"totalconc_water",3,"2020-12-08")
waterdata_18 <- loadnshapedata(n,"totalconc_water",18,"2020-12-04")
waterdata_25 <- loadnshapedata(n,"totalconc_water",25,"2020-12-04")
airdata_3 <- loadnshapedata(n,"totalconc_air",3,"2020-12-08")
airdata_18 <- loadnshapedata(n,"totalconc_air",18,"2020-12-04")
airdata_25 <- loadnshapedata(n,"totalconc_air",25,"2020-12-04")

water.data <- list("3" = waterdata_3, "18" = waterdata_18, "25" = waterdata_25)
air.data <- list("3" = airdata_3, "18" = airdata_18, "25" = airdata_25)
list.hairs <- c("3","18","25")
alldatarow.water<-stitch.rows(water.data,list.hairs)
alldatarow.air<-stitch.rows(air.data,list.hairs)

```


## Individual Row Plots


Plot gap-to-diameter ratio against value: 
```{r echo=FALSE, warning=FALSE, fig.height=11, fig.width=8.5}
row1water<-ggplot(alldatarow.water, aes(gap,row1,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Gap-to-diameter ratio") + ylab("Conc captured per row") + ylim(c(0,200)) +
  theme(legend.position = "none")
row2water<-ggplot(alldatarow.water, aes(gap,row2,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Gap-to-diameter ratio") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")
row3water<-ggplot(alldatarow.water, aes(gap,row3,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Gap-to-diameter ratio") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")
row4water<-ggplot(alldatarow.water, aes(gap,row4,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Gap-to-diameter ratio") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")
row5water<-ggplot(alldatarow.water, aes(gap,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) +
  theme(legend.position = "bottom")
leg.water<-get_legend(row5water)
row5water<-ggplot(alldatarow.water, aes(gap,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Gap-to-diameter ratio") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")

row1air<-ggplot(alldatarow.air, aes(gap,row1,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Gap-to-diameter ratio") + ylab("Conc captured per row") + ylim(c(0,30000)) +
  theme(legend.position = "none")
row2air<-ggplot(alldatarow.air, aes(gap,row2,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Gap-to-diameter ratio") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")
row3air<-ggplot(alldatarow.air, aes(gap,row3,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Gap-to-diameter ratio") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")
row4air<-ggplot(alldatarow.air, aes(gap,row4,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Gap-to-diameter ratio") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")
row5air<-ggplot(alldatarow.air, aes(gap,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Gap-to-diameter ratio") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "bottom")
leg.air<-get_legend(row5air)
row5air<-ggplot(alldatarow.air, aes(gap,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Gap-to-diameter ratio") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")

plot_grid(leg.water, leg.air,
          row1water, row1air, row2water, row2air, row3water, row3air, 
          row4water, row4air, row5water, row5air, 
          nrow = 6, labels=c("Water", "Air",
                             "row 1", " ",
                             "row 2", " ",
                             "row 3", " ",
                             "row 4", " ",
                             "row 5", " "), 
          label_x = c(0.45,0.45,0,0,0,0,0,0,0,0,0,0), 
          label_y = c(1.1, 1.1),
          rel_heights = c(0.75,2,2,2,2,2))
```



Plot Reynolds number against odor captured:
```{r echo=FALSE, fig.height=11, fig.width=8.5, warning=FALSE}
row1water<-ggplot(alldatarow.water, aes(Re,row1,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Reynolds number") + ylab("Conc captured per row") + ylim(c(0,200)) +
  theme(legend.position = "none")
row2water<-ggplot(alldatarow.water, aes(Re,row2,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Reynolds number") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")
row3water<-ggplot(alldatarow.water, aes(Re,row3,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Reynolds number") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")
row4water<-ggplot(alldatarow.water, aes(Re,row4,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Reynolds number") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")
row5water<-ggplot(alldatarow.water, aes(Re,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) +
  theme(legend.position = "bottom")
leg.water<-get_legend(row5water)
row5water<-ggplot(alldatarow.water, aes(Re,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Reynolds number") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")

row1air<-ggplot(alldatarow.air, aes(Re,row1,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Reynolds number") + ylab("Conc captured per row") + ylim(c(0,30000)) +
  theme(legend.position = "none")
row2air<-ggplot(alldatarow.air, aes(Re,row2,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Reynolds number") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")
row3air<-ggplot(alldatarow.air, aes(Re,row3,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Reynolds number") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")
row4air<-ggplot(alldatarow.air, aes(Re,row4,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Reynolds number") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")
row5air<-ggplot(alldatarow.air, aes(Re,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Reynolds number") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "bottom")
leg.air<-get_legend(row5air)
row5air<-ggplot(alldatarow.air, aes(Re,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Reynolds number") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")

plot_grid(leg.water, leg.air,
          row1water, row1air, row2water, row2air, row3water, row3air, 
          row4water, row4air, row5water, row5air, 
          nrow = 6, labels=c("Water", "Air",
                             "row 1", " ",
                             "row 2", " ",
                             "row 3", " ",
                             "row 4", " ",
                             "row 5", " "), 
          label_x = c(0.45,0.45,0,0,0,0,0,0,0,0,0,0), 
          label_y = c(1.1, 1.1),
          rel_heights = c(0.75,2,2,2,2,2))
```



Plot angle against value: 
```{r echo=FALSE, warning=FALSE, fig.height=11, fig.width=8.5}
row1water<-ggplot(alldatarow.water, aes(angle,row1,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Angle") + ylab("Conc captured per row") + ylim(c(0,200)) +
  theme(legend.position = "none")
row2water<-ggplot(alldatarow.water, aes(angle,row2,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Angle") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")
row3water<-ggplot(alldatarow.water, aes(angle,row3,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Angle") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")
row4water<-ggplot(alldatarow.water, aes(angle,row4,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Angle") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")
row5water<-ggplot(alldatarow.water, aes(angle,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) +
  theme(legend.position = "bottom")
leg.water<-get_legend(row5water)
row5water<-ggplot(alldatarow.water, aes(angle,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", discrete = TRUE) + 
  xlab("Angle") + ylab("Conc captured per row") + ylim(c(0,200)) + 
  theme(legend.position = "none")

row1air<-ggplot(alldatarow.air, aes(angle,row1,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Angle") + ylab("Conc captured per row") + ylim(c(0,30000)) +
  theme(legend.position = "none")
row2air<-ggplot(alldatarow.air, aes(angle,row2,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Angle") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")
row3air<-ggplot(alldatarow.air, aes(angle,row3,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Angle") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")
row4air<-ggplot(alldatarow.air, aes(angle,row4,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Angle") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")
row5air<-ggplot(alldatarow.air, aes(angle,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Angle") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "bottom")
leg.air<-get_legend(row5air)
row5air<-ggplot(alldatarow.air, aes(angle,row5,color=array)) +
  geom_point(size=2) + scale_color_viridis(name = "Array", option = "C", discrete = TRUE) + 
  xlab("Angle") + ylab("Conc captured per row") + ylim(c(0,30000)) + 
  theme(legend.position = "none")

plot_grid(leg.water, leg.air,
          row1water, row1air, row2water, row2air, row3water, row3air, 
          row4water, row4air, row5water, row5air, 
          nrow = 6,  labels=c("Water", "Air",
                             "row 1", " ",
                             "row 2", " ",
                             "row 3", " ",
                             "row 4", " ",
                             "row 5", " "), 
          label_x = c(0.45,0.45,0,0,0,0,0,0,0,0,0,0), 
          label_y = c(1.1, 1.1),
          rel_heights = c(0.75,2,2,2,2,2))
```


## Total Concentration Plots

Setup data frames: 
```{r echo=TRUE}
alldatawater.totalconc <- data.frame(waterdata_3[,1:3], waterdata_3$total.conc, waterdata_18$total.conc, waterdata_25$total.conc)
colnames(alldatawater.totalconc)<- c(colnames(waterdata_3[,1:3]),"3hairs","18hairs","25hairs")
alldatawaterconc.melted <- melt(alldatawater.totalconc, id.vars = c("angle","gap","Re"))
alldataair.totalconc <- data.frame(airdata_3[,1:3], airdata_3$total.conc,
                                   airdata_18$total.conc, airdata_25$total.conc)
colnames(alldataair.totalconc)<- c(colnames(airdata_3[,1:3]),"3hairs","18hairs","25hairs")
alldataairconc.melted <- melt(alldataair.totalconc, id.vars = c("angle","gap","Re"))
```

Total concentration for gap-to-diameter ratio versus odor captured, arrays as colors: 
```{r echo=FALSE,fig.height=9, fig.width=8.5}
water.gap <- ggplot(alldatawaterconc.melted, aes(gap, value, color = variable)) +
            geom_point() + scale_color_viridis(name = "Array", discrete = TRUE) +
            xlab("Gap-to-diameter ratio") + ylab("Total odor captured") +
            theme(legend.position = "top")
leg.water<-get_legend(water.gap)
water.gap <- ggplot(alldatawaterconc.melted, aes(gap, value, color = variable)) +
            geom_point() + scale_color_viridis(name = "Array", discrete = TRUE) +
            xlab("Gap-to-diameter ratio") + ylab("Total odor captured") +
            theme(legend.position = "none")
air.gap <- ggplot(alldataairconc.melted, aes(gap, value, color = variable)) +
            geom_point() + scale_color_viridis(name = "Array", discrete = TRUE, option = "C") +
            xlab("Gap-to-diameter ratio") + ylab("Total odor captured") + 
            theme(legend.position = "bottom")
leg.air<-get_legend(air.gap)
air.gap <- ggplot(alldataairconc.melted, aes(gap, value, color = variable)) +
            geom_point() + scale_color_viridis(name = "Array", discrete = TRUE, option = "C") +
            xlab("Gap-to-diameter ratio") + ylab("Total odor captured") + 
            theme(legend.position = "none")
water.Re <- ggplot(alldatawaterconc.melted, aes(Re, value, color = variable)) +
            geom_point() + scale_color_viridis(name = "Array", discrete = TRUE) +
            xlab("Reynolds number") + ylab("Total odor captured") +
            theme(legend.position = "none")
air.Re <- ggplot(alldataairconc.melted, aes(Re, value, color = variable)) +
            geom_point() + scale_color_viridis(name = "Array", discrete = TRUE, option = "C") +
            xlab("Reynolds number") + ylab("Total odor captured") + 
            theme(legend.position = "none")
water.angle <- ggplot(alldatawaterconc.melted, aes(angle, value, color = variable)) +
            geom_point() + scale_color_viridis(name = "Array", discrete = TRUE) +
            xlab("Angle") + ylab("Total odor captured") +
            theme(legend.position = "none")
air.angle <- ggplot(alldataairconc.melted, aes(angle, value, color = variable)) +
            geom_point() + scale_color_viridis(name = "Array", discrete = TRUE, option = "C") +
            xlab("Angle") + ylab("Total odor captured") + 
            theme(legend.position = "none")

plot_grid(leg.water, leg.air, water.gap, air.gap, water.Re, air.Re, water.angle, air.angle,
          nrow = 4,
          labels=c("Water", "Air"), 
          label_x = c(0.45,0.45), 
          label_y = c(1, 1),
          rel_heights = c(0.75,2,2,2),rel_widths = c(1,1))
```

```{r echo=FALSE,warning=FALSE}
all.water<-ggplot(alldatawaterconc.melted, aes(variable, value, fill=variable)) + geom_violin() +
   stat_summary(fun="mean",color="black",fill="white",pch=21, size=1.25)+
  scale_fill_viridis(name = "Array", discrete = TRUE) + 
  xlab("") + ylab("Total Conc Captured") + ggtitle("Water") +
  theme(plot.title = element_text(hjust = 0.5))

all.air<-ggplot(alldataairconc.melted, aes(variable, value, fill=variable))+geom_violin() +
  stat_summary(fun="mean",color="black",fill="white",pch=21, size=1.25)+
  scale_fill_viridis(name = "Array", discrete = TRUE, option = "C") + 
  xlab("") + ylab("Total Conc Captured") + ggtitle("Air") + 
  theme(plot.title = element_text(hjust = 0.5))
plot_grid(all.water,all.air,labels = c("Water","Air"),label_x=c(0.5,0.5),label_y=c(1.1,1.1))
```