#!/bin/bash
# SBATCH -p RM
# SBATCH -t 12:00:00
# SBATCH -N 1
# SBATCH --ntasks-per-node=8
# SBATCH --mail-type=ALL

# echo commands to stdout
set -x 

# Number of hairs in the array
array=18

# Fluid
fluid="water"

# First number
a=1

# Second number
b=8

# Set path 
WD="/pylon5/bi561lp/lwaldrop/entcode"

# move to working directory
cd "${WD}"/src/matlab

# add appropriate modules
module load matlab

# run matlab program
matlab -r "entsniff("$WD",$array,$fluid,$a:$b,8);exit"

