% Generated on 09-Jun-2015 10:41:59
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/CFD'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/CFD');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/PIV'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/PIV');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/analyzepiv'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/analyzepiv');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/angle'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/angle');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/common'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/common');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/graphics'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/graphics');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/imcorrel'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/imcorrel');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/kinematics'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/kinematics');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/neuro'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/neuro');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/ui'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/ui');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/variables'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/variables');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/wavelets'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/wavelets');
fprintf('Removing ''/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/kinematics/experimental'' from the path\n');
rmpath('/home/laura/Desktop/peristalsis_flappyends/matlab-tytell/kinematics/experimental');
savepath;
